# Generated by Django 4.1.3 on 2022-12-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cedear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=10)),
                ("precio", models.FloatField()),
                ("ratio", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Operacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cliente", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=200)),
                ("usd", models.IntegerField()),
                ("fx_rate", models.IntegerField()),
            ],
        ),
    ]
