# Generated by Django 4.1.3 on 2022-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectofinal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operacion", name="fecha", field=models.DateField(),
        ),
    ]
