# Generated by Django 4.1.3 on 2022-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectofinal", "0002_accionusa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=10)),
                ("media", models.FloatField()),
                ("sdev", models.FloatField()),
                ("weight", models.FloatField()),
            ],
        ),
    ]
