# Generated by Django 4.1.3 on 2022-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectofinal", "0003_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=10)),
                ("precio_arg", models.FloatField()),
                ("ratio", models.IntegerField()),
                ("precio_usa", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(name="AccionUSA",),
        migrations.DeleteModel(name="Cedear",),
    ]
